name: CI

on:
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - run: npm build
      - run: npm test


  Heroku:
    uses: AkhileshNS/heroku-deploy@v3.0.5
      with:
        # This will be used for authentication. You can find it in your heroku homepage account settings
        heroku_api_key: ${{ secret.DEPLOY_KEY }}
        # Email that you use with heroku
        heroku_email: xgabrielhenrique@live.com
        # The appname to use for deploying/updating
        heroku_app_name: agenda-eletronica-tcc